project:
  type: website
  render:
    - "*.qmd"
    - "!archive/"

website:
  title: "DUDE: Dutch Development Economics Network"
  description: "A website to to facilitate knowledge exchange and connections among development economists based in the Netherlands."
  open-graph:
    image: dude_banner.png
    image-alt: "Explaining an economic game to farmers in Masaka, Uganda."
  twitter-card:
    image: dude_banner.png
    image-alt: "Explaining an economic game to farmers in Masaka, Uganda."
    card-style: summary_large_image
  site-url: https://www.m-gonzalezamador.com
  favicon: images/favicon.ico
  navbar:
    background: "#472605"
    foreground: "#FFFFFF"
    title: ""
    search: true
    logo: images/logos/dude_logo_transparent.png
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - href: about/index.qmd
        text: "About"
      - href: posts/index.qmd
        text: "Posts"
      - text: "Research"
        menu:
        - href: research/highlights/index.qmd
          text: "Highlights"
      - href: members/index.qmd
        text: "Members"
      - href: events/index.qmd
        text: "Eooks"
      - href: gallery/index.qmd
        text: "Gallery"
      - href: https://github.com/michelleg06/dude_website
        icon: github
  announcement:
    icon: info-circle
    dismissable: true
    content: "This site is under construction!"
    type: warning
    position: below-navbar

format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [theme.css, custom_theme.scss]
    toc: true
    code-overflow: scroll
    linkcolor: "#B8573E"
    include-before-body: _fathom.html

freeze: true



